### ISSUE TITLE
Functionality of info button

### ISSUE THREAD

**Issue by GeorgeVarvates** [squaredev-io/GFM-UAT#11] opened 2022-06-14 12:12 UTC
What is the functionality of the following info icon 
![image](https://user-images.githubusercontent.com/64831585/173574036-dc1026b5-3d97-4076-9ae9-0b608df24c95.png)

**Comment by chris-iliopoulos** [comment] 2022-07-25 08:59
duplicate of issue #36

**Closed as completed by chris-iliopoulos** 2022-07-25 08:59 UTC
Labels: discussion needed, duplicate
