### ISSUE TITLE
Profit & Loss graph’s months are not clear at all what they depict and when they count.

### ISSUE THREAD

**Issue by chris-iliopoulos** [squaredev-io/GFM-UAT#32] opened 2022-07-06 16:42 UTC
@ksiabani

**Comment by ksiabani** [comment] 2022-07-19 14:04
Duplicate of https://github.com/squaredev-io/GFM-UAT/issues/31? I explained everything there

**Comment by chris-iliopoulos** [comment] 2022-07-19 14:13
It was not a duplicate but now it's quite clear from your answer to the previous one... The problem here is that the months should only count ACTUAL profit - loss amounts for selected months (1/4/6/12) and not the cashflow predictions (meaning two months ahead of the current month)

**Closed as completed** 2022-07-29 11:31 UTC
Labels: enhancement, High
