### ISSUE TITLE
Not able to make a payment (transfer between Eurobank accounts linked to GFM) 

### ISSUE THREAD

**Issue by nikosdouv** [squaredev-io/GFM-UAT#17] opened 2022-06-20 13:51 UTC
i added 3 eurobank accounts. i cannot transfer funds between them. Error message attached. 
![eurob trasnfer error msg](https://user-images.githubusercontent.com/107864092/174616511-7ce78f3c-d89c-4116-9572-106b41bf339b.png)

**Comment by ghost** [comment] 2022-06-22 09:57
Looks like this issue is a duplicate of #9 and there's an upcoming fix, so I'm closing this.

**Closed as completed by ghost** 2022-06-22 09:57 UTC
