### ISSUE TITLE
Cashflow graph doesn’t use the word prediction when hovering in a correct manner.

### ISSUE THREAD

**Issue by chris-iliopoulos** [squaredev-io/GFM-UAT#28] opened 2022-07-06 16:35 UTC

**Comment by awareness481** [comment] 2022-08-10 08:10
Re-opened, either a regression or it wasn't working properly in earlier versions as well.

**Comment by awareness481** [comment] 2022-08-11 06:00
Issue was on my end, because of outdated data. I confirmed it works with up to date data. Closing this again :)

**Closed as completed by awareness481** 2022-08-11 06:00 UTC
Labels: Bug, Low
